language: cpp
compiler:
  - clang
  - gcc
before_install:
  - apt-get -qq update
  - apt-get install -y libpng-dev z3
install:
  - mkdir build && cd build && cmake .. && make 
script:
  - cd test && testall
