language: cpp
sudo: required
compiler:
  - clang
  #- gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libm4ri-dev
  - ls -lhtr /usr/include/m4ri/
  - cat /usr/include/m4ri/m4ri.h
install:
  - mkdir build && cd build && cmake .. && make
script:
  - cd test && testall
