# This is a sample build configuration for other languages.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
# image: docker-image:tag

image: gcc:5.2
pipelines:
  default:
    - step:
        script:
          - sudo apt-get -qq update
          - sudo apt-get install -y libpng-dev z3
          - mkdir build && cd build && cmake .. && make 
          - cd test && testall
